### ISSUE TITLE
Remove RepyV1 support

### ISSUE THREAD

**Issue by aaaaalbert** [SensibilityTestbed/nodemanager#1]
I don't think that Sensibility Testbed should support RepyV1 at all. We don't have sensor code for it, and also all of our examples assume V2.

**Comment by JustinCappos** [comment]
I agree.  Omitting it should be as easy as modifying the StartVessel /
StartVesselEx calls.

However, there may be a few left over files that aren't needed in the
installer.

**Comment by aaaaalbert** [comment]
Fixed as per aaaaalbert/installer-packaging@e213337a968ea2f1b456bfe73b49ab60ca0a1d0c.
